version: '2.1'
orbs:
  terraform: circleci/terraform@3.2.1
workflows:
  deploy_infrastructure:
    jobs:
      - terraform/fmt:
          checkout: true
          context: terraform
          path: src/modules
          recursive: true
      - terraform/validate:
          checkout: true
          context: terraform
          path: src/modules/cluster_settings
          requires:
            - terraform/fmt
      - terraform/validate:
          checkout: true
          context: terraform
          path: src/modules/component_templates
          requires:
            - terraform/fmt
      - terraform/validate:
          checkout: true
          context: terraform
          path: src/modules/ilm_policies
          requires:
            - terraform/fmt