version: '2.1'
orbs:
  terraform: circleci/terraform@3.2.1
workflows:
  deploy_infrastructure:
    jobs:
      - terraform/validate:
          checkout: true
          context: terraform
          path: src/modules/cluster_settings
      - terraform/validate:
          checkout: true
          context: terraform
          path: src/modules/component_templates
      - terraform/validate:
          checkout: true
          context: terraform
          path: src/modules/ilm_policies